### ISSUE TITLE
License is not open source

### ISSUE THREAD

**Issue by davelab6** [roberto-arista/PythonForDesigners#3]
This is a fantastic work! Congratulations :)

I was excited to see the project, and happy to read,

> This manual is open-source, free to read and free from ads

However, I was then sad to see that currently it is licensed under the cc-by-sa-nc license, and the nc means it is not open source as defined by the OpenSource.org Initiative.

I myself and many people in positions like mine can't contribute at all, since my employer owns the copyrights to my work, and while it's very easy for me to contribute to projects that are under licences approved by the OSI, I'll not be allowed to here.

I hope you'll consider the license used by Wikipedia, cc-by-sa, or a software license that can be used for other works like GPL v3. Both are "copyleft" licenses that permit commercial use and contribution, but require all derivatives to remain under the same license, which prevents rude exploitation and encourages improvements to be contributed back to you project.

If you start to include contributions from other people under the current license, it be difficult to change it ever again as you may need to contact them all and get their permission too.... 

Would you consider a different license?

**Comment by roberto-arista** [comment]
I understand your issue but consider the following scenario: a publishing house – usually publishing many Python books every year – finds this website and decides to make a quick printed book out of it. I mean, the content is mostly ready. It's a bad move, but they can do that.

The aspect that will hurt me more is not the money, but the fact they can mess with content and illustrations as they like without my consent.

With this license, they cannot, but people can still read it, copy it, use it, as soon as they are not making money out of it. I believe it makes sense because this manual is not meant to be used to make something out it as a tool, instead to learn how to make something. I believe people should be able to make a living out of the stuff they learn, not the books where they learn it. 

I hope I was able to express my concerns. If you have any recommendation of licenses which will make this work completely open source and still protect it, I will consider it.

**Comment by roberto-arista** [comment]
btw, I removed "open-source" from the home page.
I will seriously think about it, but I am not going to rush this kind of decision.
I need to get more info about the possible scenarios.

**Comment by davelab6** [comment]
Removing open source is a great idea! Thanks for that :) 

I'm in NYC and happy to chat through scenarios any time
